package com.github.fribourgsdp.radio

import com.github.fribourgsdp.radio.Genre.*

object StarterPlaylists {
    val top100french = Playlist("Chanson française 80\'s", FRENCH)
    init {
        top100french.addSongs(setOf(
            "Indochine" to "L\'aventurier",
            "Jean-Jacques Goldman, Michael Jones" to "Je te donne",
            "Marc Lavoine" to  "Elle a les yeux revolver",
            "Jacques Brel" to "Ne me quitte pas",
            "Charles Trenet" to "La mer",
            "Barbara" to "L’aigle noir",
            "Edith Piaf" to "Hymne à l’amour",
            "Léo Ferré" to "Avec le temps",
            "Yves Montand" to "Les feuilles mortes",
            "Georges Brassens" to "Les copains d’abord",
            "Charles Aznavour" to "La bohème",
            "Georges Brassens" to "Chanson pour l’Auvergnat",
            "Céline Dion" to "Pour que tu m’aimes encore",
            "Yves Duteil" to "Prendre un enfant",
            "Jacques Brel" to "Quand on n’a que l’amour",
            "Henri Salvador" to "Syracuse",
            "Claude François" to "Comme d’habitude",
            "Jacques Brel" to "Le plat pays",
            "Edith Piaf" to "La vie en rose",
            "Jean Ferrat" to "La montagne",
            "Jacques Dutronc" to "Il est cinq heures Paris s’eveille",
            "Jacques Brel" to "Amsterdam",
            "Yves Duteil" to "La langue de chez nous",
            "Beau Dommage" to "La complainte du phoque en Alaska",
            "Nino Ferrer" to "Le sud",
            "Michel Sardou" to "La maladie d’amour",
            "Edith Piaf" to "Milord",
            "Gilbert Bécaud" to "Nathalie",
            "Joe Dassin" to "L’été indien",
            "Serge Gainsbourg" to "La Javanaise",
            "Francis Cabrel" to "Petite Marie",
            "Francis Cabrel" to "L’encre de tes yeux",
            "Jacques Brel" to "Les vieux",
            "Claude Dubois" to "Le blues du businessman",
            "Edith Piaf" to "Non, je ne regrette rien",
            "Léo Ferré" to "C’est extra",
            "Yves Duteil" to "Pour les enfants du monde entier",
            "Cora Vaucaire" to "Le temps des cerises",
            "Johnny Hallyday" to "Que je t’aime",
            "Fabienne Thibeault" to "Les uns contre les autres",
            "Jean Ferrat" to "Que serais-je sans toi?",
            "Francis Cabrel" to "Je l’aime à mourir",
            "Serge Gainsbourg" to "La chanson de Prévert",
            "Georges Brassens" to "Les amoureux des bancs publics",
            "Serge Gainsbourg" to "Le poinçonneur des Lilas",
            "Jean-Jacques Goldman" to "Là-bas",
            "Joe Dassin" to "Les Champs-Elysées",
            "Laurent Voulzy" to "Belle-Île-En-Mer…",
            "Gérard Lenorman" to "La ballade des gens heureux",
            "Raymond Levesque" to "Quand les hommes vivront d’amour",
            "Alain Souchon" to "Foule sentimentale",
            "Edith Piaf" to "La foule",
            "Félix Leclerc" to "Le petit bonheur",
            "Daniel Guichard" to "Mon vieux",
            "Claude Léveillée" to "Frédéric",
            "Daniel Lavoie" to "Ils s’aiment",
            "Julien Clerc" to "Ma préférence",
            "Daniel Balavoine" to "L’Aziza",
            "Barbara" to "Ma plus belle histoire d’amour",
            "Hugues Aufray" to "Céline",
            "Charles Trenet" to "L’âme des poètes",
            "Robert Charlebois" to "Lindberg",
            "Maxime Le Forestier" to "San Francisco",
            "Lucienne Boyer" to "Parlez-moi d’amour",
            "Boris Vian" to "Le déserteur",
            "Gilles et les Compagnons" to "Les trois cloches",
            "Nino Ferrer" to "La maison près de la fontaine",
            "Jean Ferrat" to "C’est beau la vie",
            "Françoise Hardy" to "Message personnel",
            "Félix Leclerc" to "L’hymne au printemps",
            "Gilles Vigneault" to "Mon pays",
            "Guy Béart" to "L’eau vive",
            "Tino Rossi" to "Petit Papa Noël",
            "Christophe" to "Aline",
            "Salvatore Adamo" to "Inch’ Allah",
            "Gilbert Bécaud" to "Et maintenant",
            "Lucille Dumont" to "Le ciel se marie avec la mer",
            "Berthe Sylva" to "Les roses blanches",
            "Michel Fugain" to "Une belle histoire",
            "Julien Clerc" to "Femmes je vous aime",
            "Jean-Pierre Ferland" to "Je reviens chez nous",
            "Serge Gainsbourg" to "Je suis venu te dire",
            "Georges Moustaki" to "Il y avait un jardin",
            "Fabienne Thibeault" to "Ziggy",
            "Claude Nougaro" to "Tu verras",
            "Il était une fois" to "J’ai encore rêvé d’elle",
            "Eddy Mitchell" to "Couleur menthe à l’eau",
            "Maurane" to "Sur un prélude de Bach",
            "Pauline Julien" to "L’âme à la tendresse",
            "Mireille Mathieu" to "Mille colombes",
            "Johnny Hallyday" to "Quelque chose de Tennessee",
            "Serge Reggiani" to "Il suffirait de presque rien",
            "Jacques Brel" to "La quête",
            "Léo Ferré" to "Vingt ans",
            "Laurent Voulzy" to "Le coeur grenadine",
            "Félix Leclerc" to "Le tour de l’île",
            "Georges D’or" to "La Manic",
            "Charles Aznavour" to "La Mamma",
            "Charles Trenet" to "Y a d’la joie",
            "Pierre Perret" to "Lily",
            "Dick Annegarn" to "Bruxelles",
            "France Gall" to "Si maman si",
            "Charles Trenet" to "Douce France",
            "Jacques Brel" to "Amsterdam"
        ).map { tuple -> Song(tuple.second, tuple.first) }.toSet())
    }
}