package com.github.fribourgsdp.radio.database

/**
 * Constants used by the Firestore database
 */
const val SONG_CHOICES_KEY = "song_choices"
const val WITH_HINT_KEY = "withHint"
const val SINGER_DURATION_KEY = "singerDuration"
const val NO_SING_KEY = "noSing"
const val PRIVATE_KEY = "private"
const val NB_ROUNDS_KEY = "nbRounds"
const val PLAYLIST_KEY = "playlist"
const val NAME_KEY = "name"
const val HOST_KEY = "host"
const val FINISHED_KEY = "finished"
const val CURRENT_ROUND_KEY = "current_round"
const val SINGER_KEY = "singer"
const val SCORES_KEY = "scores"
const val VALIDITY_KEY = "validity"
const val SONG_CHOICES_LYRICS_KEY = "song_choices_lyrics"
const val PLAYER_DONE_MAP_KEY = "player_done_map"
const val PLAYER_FOUND_MAP_KEY = "player_found_map"
const val SCORES_OF_ROUND_KEY = "scores_of_round"
const val USERNAME_KEY = "username"
const val USER_ID_KEY = "userID"
const val ROUND_DEADLINE_KEY = "round_deadline"
const val CURRENT_SONG_KEY = "current_song"
const val PLAYERS_KEY = "players"
const val PERMISSIONS_KEY = "permissions"
const val SONG_ID_KEY = "songId"
const val SONG_NAME_KEY = "songName"
const val ARTIST_NAME_KEY = "artistName"
const val LYRICS_KEY = "lyrics"
const val GENRE_KEY = "genre"
const val PLAYLIST_NAME_KEY = "playlistName"
const val PLAYLIST_ID_KEY = "playlistId"
const val LAUNCHED_KEY = "launched"

const val USER_COLLECTION_PATH = "user"
const val SONGS_COLLECTION_PATH = "songs"
const val PLAYLISTS_COLLECTION_PATH = "playlists"
const val LOBBY_COLLECTION_PATH = "lobby"
const val GAMES_METADATA_COLLECTION_PATH = "games_metadata"
const val GAMES_COLLECTION_PATH = "games"
const val METADATA_COLLECTION_PATH = "metadata"

const val PUBLIC_DOCUMENT_PATH = "public"
const val ID_DOCUMENT_PATH = "id"
const val SONG_INFO_DOCUMENT_PATH = "SongInfo"
const val USER_INFO_DOCUMENT_PATH = "UserInfo"
const val PLAYLIST_INFO_DOCUMENT_PATH = "PlaylistInfo"
